### PR TITLE
Custom message templating

### PR DESCRIPTION
**Pull request by shads2**
I still need to write documentation so not merge-able yet.

This implements templatable messaging as well as stateful notifications

### CODE REVIEW

**Comment by jrbartola** [comment]
Hm- stateful alerts have already been implemented, or at least I had implemented them a few weeks back (38c625e)

**Comment by shads2** [comment]
Oh, the git issue was left open and I don't remember seeing the PR for it.

Done now though I guess ¯\\\_(ツ\)_\/¯

**Comment by jrbartola** [comment]
Sounds good. Ready for merging?

**Comment by shads2** [comment]
Ready to ship!

**Pull request merged**
