### PR TITLE
Multiple indicators

### PR DESCRIPTION
**Pull request by jrbartola**
Added the ability to watch multiple indicators with different period lengths.

### CODE REVIEW

**Comment by shads2** [comment]
There isn't really anything wrong with this change, though I think we may also want to consider another approach.

Instead of a tuple of values, we may wish to change the indicators to instead be a list of indicators. This would give some additional flexibility...
1. The ability to tune every setting individually for each duplicate indicator.
2. The ability to analyze crossovers of different indicator types, for example looking at crossovers of EMA and SMA is sometimes a thing people care about. We could create a new kind of indicator called a post-analysis indicator for these kind of checks and have them reference which indicators in a set they want to use for the test.

So instead of doing
```
'ema': {
'enabled': True,
'alert_enabled': True,
'hot': 1,
'cold': 1,
'candle_period: '1d',
'period_count': 11/15
}
```

We could do
```
'ema': [
{
'enabled': True,
'alert_enabled': True,
'hot': 1,
'cold': 1,
'candle_period: '1d',
'period_count': 11
},
{
'enabled': True,
'alert_enabled': True,
'hot': 1,
'cold': 1,
'candle_period: '1d',
'period_count': 15
}
]
```

With the default settings to be found at array element 0, which means environment variable settings would need to look something like 'BEHAVIOUR_EMA_ENABLED_0' and so on for each list item added.

What do you think?

**Comment by jrbartola** [comment]
The reason I made the Crossover Periods into 2-tuples is because crossovers are only well-defined when comparing two different values. All other indicators take a list of comma-separated integers (i.e., 15,21,50), but I like the idea of storing each indicator configuration in a list so we can provide maximum flexibility

**Comment by shads2** [comment]
For sure, I totally see where you were going and that was also my instinct as well. The list idea came to me later today after reading your PR. We could merge this for now and refactor later? Up to you how you want to proceed. Maybe make another git issue if you decide to merge this in its current form.

**Comment by cryptohanaan** [comment]
Hi guys, my two cents here. As I see EMA (and SMA) they are always a cross. Sometime between two periods and sometimes between a period and the close-value, (which is really just EMA/SMA with a period of 1 (average of the last candle only). In any case, there are no more than two.
With that in mind, what about this setup?
It allows for multiple EMAs, each one is either a cross between two EMAs or just an EMA and the close.
This also gives us a framework to allow other indicators to have multiple values.

```
'ema': [
{
'enabled': True,
'alert_enabled': True,
'hot': 1,
'cold': 1,
'candle_period: '1d',
**'period_count_1': 11,**
**'period_count_2': 26**
},
{
'enabled': True,
'alert_enabled': True,
'hot': 1,
'cold': 1,
'candle_period: '4h',
**'period_count_1': 1,**
**'period_count_2': 9**
},
```

**Comment by jrbartola** [comment]
@cryptohanaan Thanks for the input. I think it would make more sense to maintain a distinction between the crossovers and individual indicators themselves, as the logic underpinning their output is very different. I'll try to get @shads2 's suggested changes merged in by the end of today

**Comment by jrbartola** [comment]
This PR is still in progress. Not mergable until further notice

**Pull request closed without merging**
